---
title: "A Questão Agrária"
subtitle: "no Brasil e no Mundo"
author: "Luiz F. P. Droubi"
date: "`r format(Sys.Date(), '%d/%m/%Y')`"
output:
  pdf_document:
    includes:
      in_header: preamble.tex
    keep_tex: yes
    latex_engine: xelatex
    number_sections: yes
    toc: no
  word_document: default
  html_document:
    fig_caption: yes
    keep_md: yes
classoption: a4paper, 12pt
documentclass: article
geometry: left=3.5cm,right=2.5cm,top=2.5cm,bottom=2.5cm
link-citations: yes
linkcolor: red
urlcolor: magenta
citecolor: green
csl: ABNT_UFPR_2011-Mendeley.csl
bibliography: bibliography.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'),
                      echo = FALSE)
options(htmltools.dir.version = FALSE)
```

# Resumo {-}

Este trabalho foi desenvolvido para obtenção de conceito na Disciplina TGT4100181 do Programa de Pós-Graduação em Engenharia de Transportes e Gestão Territorial da UFSC -- Cadastro Técnico Multifinalitário. Teve como motivação as três condições, elencadas por Pereira [-@questaoagraria], como necessárias à implantação da reforma agrária, quais sejam: **a.** que haja no país uma alta concentração de renda; **b.** que haja verdadeira miséria rural no País e; **c.** que haja relação entre a reforma agrária e o desenvolvimento nacional. Pra nós claro está que as condições **a.** e **b.** estão desde há muito tempo intocadas no Brasil, ou seja, estão presentes desde a origem. Coube-nos investigar se há verdadeira relação, ainda, entre a reforma e o desenvolvimento.

# Introdução

> Do ponto de vista social, todos os fatores se resumem em um "recurso" elementar: o homem. Logo, não é possível seguir conceptualmente o processo de industrialização se não sabemos como o homem aplicava antes o seu tempo de trabalho, como o aplica depois, o que ocorre quando passa de um modo de produzir a outra e em que condições realiza essa passagem.[...] Considerando que na estrutura da economia que precede a industrialização quase toda a população está na "agricultura", é preciso estudar detidamente a organização deste setor. Em outras palavras, se o problema da "agricultura" não foi entendido, tampouco será possível compreender o problema da "indústria", ou manufatura, nem o papel que os serviços desempenham. Falando de modo sucinto, a "manufatura" e os serviços são novas formas de aplicação de parte do tempo de trabalho da população que antes estava na "agricultura". Mas, por sua vez, a própria "agricultura" se reorganiza quando a tranferência ocorre.[@rangel1954, 89]

O desenvolvimento do capitalismo brasileiro no século XX se deu pela chamada "via prussiana" ou *junker* [@rangel1988, 155], que é um tipo de reforma agrária que consiste na substituição do latifúndio feudal pelo latifúndio capitalista. Este tipo de desenvolvimento tem como característica se dar sem a execução prévia da reforma agrária -- no sentido da distribuição dos latifúndios em pequenas propriedades, como ocorre na via clássica ou democrática.

Apesar de permitir imprimir um "impulso extraordinário e energético" à industrialização, a via prussiana "promove uma distribuição muito desigual da renda" [@rangel1988, 155]. característica talvez mais perniciosa do desenvolvimento capitalista por esta via se dá pela formação de um "exército industrial de reserva" demasiado grande, ou seja, um aumento da população urbana desproporcional à necessidade de mão-de-obra necessária nas indústrias do capitalismo nascente nas cidades. O resultado é o crescimento acelerado e desordenado das cidades, com a inevitável formação dos cortiços e favelas para acomodar a parte mais carente da população que, expulsa do campo, vai se aglomerar nos grandes centros urbanos em busca da sua sobrevivência.

Dados compilados pela ONU foram organizados na tabela abaixo com o intuito de demonstrar o tamanho exato deste problema.

|País/Região                    | Ano   ||||||
|:------------------------------|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
|                               | 1960  | 1970  | 1980  | 1990  | 2000  | 2015  |
| Mundo                         | 33,8% | 36,6% | 39,3% | 43,0% | 46,7% | 53,9% | 
| Países desenvolvidos (a)      | 61,1% | 66,8% | 70,3% | 72,4% | 74,2% | 78,1% |
| Países menos desenvolvidos (b)| 21,9% | 25,3% | 29,4% | 34,9% | 40,1% | 49,0% |
| Europa                        | 57,4% | 63,1% | 67,6% | 69,9% | 71,1% | 73,9% |
| Europa oriental               | 48,9% | 56,6% | 63,8% | 68,0% | 68,2% | 69,3% |
| Europa ocidental              | 68,6% | 72,1% | 73,4% | 74,0% | 76,0% | 79,4% |
| EUA                           | 70,0% | 73,6% | 73,7% | 75,3% | 79,1% | 81,7% |     
| Brasil                        | 46,1% | 55,9% | 65,5% | 73,9% | 81,2% | 85,8% |

Table: População urbana (%). Fonte: O autor.

a) Europa, América do Norte, Austrália/Nova Zelândia e Japão.  
b) Africa, Ásia (menos Japão), América Latina e Caribe mais Melanesia e Micronesia.

Em meados dos anos 60, apenas 46,1% da população brasileira era urbana, uma proporção bem menor do que a dos países do então primeiro mundo (EUA e Europa Ocidental), hoje ditos desenvolvidos, que girava então em torno dos 70% da população. 

Em apenas 10 anos, já em meados da década de 70, este número sofria um aumento vertiginoso de quase 10 pontos percentuais, com 55,9% da população urbana. A população urbana brasileira equiparava-se à da Europa Oriental.

Já na década de 80 a população urbana no Brasil ultrapassaria a da Europa Oriental, chegando à valores próximos da média para o continente europeu como um todo (ocidental e oriental), enquanto a população urbana no mundo desenvolvido se estagnava.

Chegado os anos 90, a população urbana brasileira atingiu notáveis 73,9% da população brasileira, número equiparado ao da população urbana do mundo desenvolvido (74% na Europa Oriental).

Em meados dos anos 2000, já então no século atual, ousamos ultrapassar, em proporção, a população urbana da Europa Oriental e a dos EUA, chegando ao último dado de 2015, com 85,8% da população brasileira vivendo nas cidades.

Há de se levar em consideração, ainda, que este "êxodo rural" ainda foi acompanhado de um crescimento demográfico expressivo.

Todo este crescimento expressivo seria salutar se tivesse se dado no contexto do rápido desenvolvimento da economia nacional. Isto, porém, não ocorreu durante todo o período analisado. O crescimento da economia brasileira acelerou-se na segunda quadra da década de 60 e manteve-se alto até fins da década seguinte, porém estagnou-se na década de 80, a chamada década perdida, sem que com isso a população urbana deixasse de crescer vertiginosamente.

Para Rangel [@rangel1986a, 151], "essa redistribuição da população entre os quadros urbano e rural não tem, em si mesma, nada de anormal.[...] A urbanização, em si mesma, é um fenômeno perfeitamente normal, numa economia em processo de industrialização. O que não é normal é o ritmo que imprimimos ao *nosso* processo de urbanização, que implica criar, nas cidades, uma oferta de mão-de-obra em descompasso com a demanda que a industrialização vai criando."

Todo este processo só poderia, então, ter desaguado no inchaço das principais cidades brasileiras. Desnecessário dizer que o planejamento urbano nestas condições é praticamente inviável. As administrações municipais, nem que fossem as mais eficientes, teriam capacidade de planejar e disciplinar o uso do solo urbano nesta "velocidade migratória".

Para Rangel [-@rangel1988, 156-157], com o desenvolvimento da indústria pesada no Brasil, a crise agrária, antes cíclica, tornou-se crônica, criando um "vasto deslocamento de população, na direção geral campo-cidade. Esse movimento se faz escalonadamente, das áreas rurais para as cidades pequenas; destas para as médias e grandes, e posteriormente para as metrópoles gigantes. No fim da linha, portanto, vamos encontrar as cidades de São Paulo e do Rio de Janeiro". Enfim, para Rangel, a origem deste "multidinário deslocamento demográfico", está "o modo como o país preparou sua estrutura agrária para a industrialização".

# Contexto histórico

O Capitalismo é um sistema político-econômico que, historicamente, substitui o Feudalismo, sistema em que a população encontrava-se toda concentrada no campo.

Nas sociedades pré-capitalistas, a população predominante rural organizava-se no chamado 'Complexo Rural', ou seja, eram produzidos pelo camponês não apenas os produtos agrícolas, mas todo o ferramental necessário, suas vestes e utensílios.

A passagem do sistema feudal para o sistema capitalista ocorre com a divisão social do trabalho, ou seja, com o desenvolvimento de indústrias que vão aos poucos absorver as atividades não-agrícolas realizadas no campo.

> Numa economia em expansão, com crescente industrialização, comercialização e  urbanização, numerosos processos anteriormente levados a efeito antes dentro da casa da família ou unidade (econômica) famíliar, ou são completamente abandonados ou substituídos por processos semelhantes em bases comerciais.(@kuznets [p. 41] *apud* @rangel1956 [p. 218])

# Feudalismo

No feudalismo, tipo de organização social que historicamente antecede o capitalismo, toda terra está concentrada nas mãos do rei.

As "leis" que regem uma sociedade feudal são:

* *All land is king's land*
* *Nulle terre sans seigneur*

Segundo Rangel [-@rangel1961, 219], "a existência de terra livre é incompatível com o feudalismo", e , por conta disto, "nas condições feudais, não tem preço e é, de fato ou de direito, inalienável"[@rangel1960, 206].

## A crise do feudalismo

A sociedade feudal entra em crise quando a produção agrícola não consegue suprir a demanda da superpopulação gerada.

Segundo Rangel [-@rangel1961, 219], "tempo houve em que a expansão do estoque populacional era objetivamente a maneira mais eficaz de expandir as forças produtivas e o produto social. Nesse tempo (regime feudal), a riqueza dos príncipes se media pelas almas dos seus domínios, e aumentar o número destas era a maneira óbvia de expandir aquela riqueza e também a do corpo social. Este foi forjando para si uma ética, um direito e uma política conducentes a esse resutado".

## O Complexo Rural

> A população de um páis de economia mercantil debilmente desenvolvida (ou não densevolvida de todo) é quase exclusivamente agrícola. Todavia, não se deve deduzir daí que ela se ocupa só da agricultura. Significa apenas que a população ocupada na agricultura transforma, ela mesma, os produtos da terra, sendo quase inexistentes o intercâmbio e a divisão do trabalho. (LENIN *apud* @rangel1954 [p. 99])

Segundo Rangel [-@rangel1956, p.98], a unidade agrícola fechada é "um microcosmo econômico no qual as pessoas distribuem seu tempo entre numerosas atividades. Cada uma dessas atividades representa o estado rudimentar daquilo que, com o desenvolvimento, se tornará uma 'indústria' (...) É evidente que o camponês não tem consciência da multiplicidade de suas atividades. Ele considera que elas formam um todo indivisível. Essa inespecialização é sua especialidade. (...) Chamaremos esse microcosmo econômico, essa 'matriz de insumo-produto' em miniatura, de 'complexo rural'".

## Condições e Métodos de abertura do Complexo Rural

> A Abertura do Complexo Rural não é uma operação momentânea, mas sim um largo processo, com altos e baixos e problemas sempre novos. Sua história está muito longe de ser idílica. Ao contrário, está cheia de violência. Uma planificação econômica que não resolva preliminarmente este problema é inconcebível. Alternadamente, pode conduzir à liberação de mais fatores que aqueles que os setores não agrícolas podem usar, fazendo toda a economia submergir em uma crise profunda, ou condenar esses setores à estagnação por insuficiência de fatores.[@rangel1954, p. 118]

Para a abertura do Complexo Rural é necessário que haja vantajosidade para a economia de mercado e para a economia natural do próprio Complexo.

As medidas tendentes a romper o complexo rural podem ser classificadas em dois grupos [@rangel1954, 113]:

a. as que oferecem um incentivo positivo para a incorporação, à economia de mercado, dos fatores usados pelo complexo e;

b. as que buscam forçar a abertura do complexo a partir de dentro, provocando uma deterioração da produtividade das atividades manufatureiras dentro do complexo.

As medidas do tipo a) temm seu exemplo mais típico nos EUA e também na França, enquanto as medidas do tipo b) predominaram na Inglaterra, Alemanha e Japão [@rangel1954, 114-115].

# Êxodo rural e industrialização

> A revolução democrático-burguesa, nos casos em que a gleba feudal é -- como aconteceu na Europa Ocidental (principalmente, na França) e nos Estados Unidos -- substituída pela pequena propriedade familiar ou *homestead*, ao fortalecer as bases da economia natural ou de autoconsumo, resolve satisfatoriamente o problema na absorção dos excedentes de mão-de-obra no seio da própria economia camponesa, estancando ou reduzindo drasticamente o fluxo populacional responsálve pelo êxodo campo-cidade [@rangel1986b, 133].

Segundo, Rangel, no entanto, "esse tipo de superação das relações de produção feudais não é característico do Brasil. Sem embargo do surgimento de algumas 'ilhas' de pequena propriedade camponse, notadamente nas áreas de colonização européia e japonesa nos estados do Sul, que mais confirmam a regra."

Ocorre que, de acordo com Rangel, "a superabundância e a barateza da mão-de-obra não costumam ser bons condicionanetes do processo de industrialização, dado que desestimulam a formação de capital, isto é, o inestimento. Ora, numa economia capitalista, o investimento é o motor primário do desenvolvimento ...". 

Por este motivo, a "economia brasileira, nas condições de uma crise agrária profunda e crônica que, entre outras coisas, **causava uma urbanização monstruosa**, sem comparação possível com a demanda de mão-de-obra que a indústria e os serviços não-agrícolas estavam suscitando nas cidades (perto de três milhões de novos citadinos a cada ano)..."

## O êxodo rural como obstáculo ao desenvolvimento

No capitalismo, é conhecido o papel do investimento ou formação de capital nas taxas de desemprego. Segundo Rangel [-@rangel1988, 156], "por um lado, via efeito multiplicador (efeito para trás), o investimento cria emprego de mão-de-obra; por outro lado, via implementação de nova tecnologia, promove dispensa de mão-de-obra (efeito para frente)". 

Segundo Rangel [@rangel1986c, 142], um "'exército industrial de reserva' limitado, isto é, algum desemprego, pode ser considerado útil, do ponto de vista da produção capitalista, porque serve de instrumento de coerção para os trabalhadores livres, fortalecendo assim a disciplina no trabalho". No entanto, quando este torna-se excessivo, "pode converter-se em obstáculo ao desenvolvimento da própria economia capitalista. Ora, aqui está o nosso problema, dado que o 'exército industrial de reserva' brasileiro tornou-se teratologicamente grande. Por isso mesmo, a questão agrária, que se exprime precipuamente pela formação desse 'exército', não interessa apenas aos camponeses, mas à sociedade como um todo."

De acordo com Rangel [-@rangel1988, 156], "a via democrática -- divisão dos latifúndios em pequenas propriedades -- ao favorecer uma distribuição menos desigualitária de re da cria condições para um vigoroso efeito multiplicador dos investimentos, isto é, forte efeito para trás. Inversamente, a via prussiana, ao promover uma distribuição de renda mais desigualitária, debilita o efeito multiplicador, isto é, para trás, mas, por força da concentração de renda, aumenta o peso relativo dos investimentos dispensando mão-de-obra e, por isso mesmo, aumentando o efeito para diante."

# Referências {-}
